### ISSUE TITLE
lv2 fails to build with Python 3.7 (newer waf required?)

### ISSUE THREAD

**Issue by bsiegert** [drobilla/lv2#25]
I am trying to build lv2-0.14.0 from source within pkgsrc, the NetBSD package collection. My Python interpreter is Python 3.7, and the build fails while configuring. 

For serd and sord, similar failures went away when I upgraded the packages to their newest versions. I assume that they bundle a more recent waf version that is compatible with Python 3.7.

Would it be possible to release a 0.14.1 or so that just updates the bundled version of waf? Thanks in advance :)

**Comment by bsiegert** [comment]
For reference, here is the build log for 0.14.0:

```
cd /usr/pkgsrc/audio/lv2/work/lv2-1.14.0 &&  /usr/bin/env FREETYPE_CONFIG=/usr/pkg/bin/freetype-config PTHREAD_CFLAGS=\ -pthread\  PTHREAD_LDFLAGS=\ -pthread PTHREAD_LIBS= PTHREADBASE=/usr DL_CFLAGS=\ -pthread\  DL_LDFLAGS=\ -pthread DL_LIBS= INSTALL_INFO= MAKEINFO=/usr/pkgsrc/audio/lv2/work/.tools/bin/makeinfo FLEX= BISON= PKG_CONFIG=/usr/pkgsrc/audio/lv2/work/.tools/bin/pkg-config PKG_CONFIG_LIBDIR=/usr/pkgsrc/audio/lv2/work/.buildlink/lib/pkgconfig:/usr/pkgsrc/audio/lv2/work/.buildlink/share/pkgconfig PKG_CONFIG_LOG=/usr/pkgsrc/audio/lv2/work/.pkg-config.log PKG_CONFIG_PATH= MAKE=make CWRAPPERS_CONFIG_DIR=/usr/pkgsrc/audio/lv2/work/.cwrapper/config PYTHON=/usr/pkg/bin/python3.7 CC=gcc CFLAGS=-O2\ -D_FORTIFY_SOURCE=2\ -I/usr/pkg/include\ -I/usr/include\ -I/usr/pkg/include/libdrm\ -I/usr/pkg/include/freetype2\ -I/usr/pkg/include/glib/glib-2.0\ -I/usr/pkg/include/glib/gio-unix-2.0\ -I/usr/pkg/lib/glib-2.0/include\ -I/usr/pkg/include/python3.7 CPPFLAGS=-I/usr/pkg/include\ -I/usr/include\ -I/usr/pkg/include/libdrm\ -I/usr/pkg/include/freetype2\ -I/usr/pkg/include/glib/glib-2.0\ -I/usr/pkg/include/glib/gio-unix-2.0\ -I/usr/pkg/lib/glib-2.0/include\ -I/usr/pkg/include/python3.7 CXX=c++ CXXFLAGS=-O2\ -D_FORTIFY_SOURCE=2\ -I/usr/pkg/include\ -I/usr/include\ -I/usr/pkg/include/libdrm\ -I/usr/pkg/include/freetype2\ -I/usr/pkg/include/glib/glib-2.0\ -I/usr/pkg/include/glib/gio-unix-2.0\ -I/usr/pkg/lib/glib-2.0/include\ -I/usr/pkg/include/python3.7 COMPILER_RPATH_FLAG=-Wl,-R F77=gfortran FC=gfortran FFLAGS=-O LANG=C LC_ALL=C LC_COLLATE=C LC_CTYPE=C LC_MESSAGES=C LC_MONETARY=C LC_NUMERIC=C LC_TIME=C LDFLAGS=-L/usr/pkg/lib\ -Wl,-R/usr/pkg/lib\ -L/usr/lib\ -Wl,-R/usr/lib LINKER_RPATH_FLAG=-R PATH=/usr/pkgsrc/audio/lv2/work/.cwrapper/bin:/usr/pkgsrc/audio/lv2/work/.buildlink/bin:/usr/pkgsrc/audio/lv2/work/.gcc/bin:/usr/pkgsrc/audio/lv2/work/.tools/bin:/usr/pkg/bin:/home/bsiegert/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R7/bin:/usr/X11R6/bin:/usr/pkg/bin:/usr/pkg/sbin:/usr/games:/usr/local/bin:/usr/local/sbin:/usr/pkg/bin:/usr/pkg/bin PREFIX=/usr/pkg MAKELEVEL=0 CONFIG_SITE= PKG_SYSCONFDIR=/usr/pkg/etc CXXCPP=cpp HOME=/usr/pkgsrc/audio/lv2/work/.home CWRAPPERS_CONFIG_DIR=/usr/pkgsrc/audio/lv2/work/.cwrapper/config /usr/pkg/bin/python3.7 ./waf configure  --destdir=/usr/pkgsrc/audio/lv2/work/.destdir --mandir=/usr/pkg/man  --copy-headers    
Traceback (most recent call last):
  File "/usr/pkgsrc/audio/lv2/work/lv2-1.14.0/.waf3-1.8.22-3bda1ef52b63839f28c19902ea6baf8f/waflib/Node.py", line 312, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/pkgsrc/audio/lv2/work/lv2-1.14.0/.waf3-1.8.22-3bda1ef52b63839f28c19902ea6baf8f/waflib/Scripting.py", line 114, in waf_entry_point
    run_commands()
  File "/usr/pkgsrc/audio/lv2/work/lv2-1.14.0/.waf3-1.8.22-3bda1ef52b63839f28c19902ea6baf8f/waflib/Scripting.py", line 171, in run_commands
    parse_options()
  File "/usr/pkgsrc/audio/lv2/work/lv2-1.14.0/.waf3-1.8.22-3bda1ef52b63839f28c19902ea6baf8f/waflib/Scripting.py", line 144, in parse_options
    Context.create_context('options').execute()
  File "/usr/pkgsrc/audio/lv2/work/lv2-1.14.0/.waf3-1.8.22-3bda1ef52b63839f28c19902ea6baf8f/waflib/Options.py", line 146, in execute
    super(OptionsContext,self).execute()
  File "/usr/pkgsrc/audio/lv2/work/lv2-1.14.0/.waf3-1.8.22-3bda1ef52b63839f28c19902ea6baf8f/waflib/Context.py", line 93, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/usr/pkgsrc/audio/lv2/work/lv2-1.14.0/.waf3-1.8.22-3bda1ef52b63839f28c19902ea6baf8f/waflib/Context.py", line 134, in recurse
    user_function(self)
  File "/usr/pkgsrc/audio/lv2/work/lv2-1.14.0/wscript", line 25, in options
    opt.load('compiler_c')
  File "/usr/pkgsrc/audio/lv2/work/lv2-1.14.0/.waf3-1.8.22-3bda1ef52b63839f28c19902ea6baf8f/waflib/Context.py", line 90, in load
    fun(self)
  File "/usr/pkgsrc/audio/lv2/work/lv2-1.14.0/.waf3-1.8.22-3bda1ef52b63839f28c19902ea6baf8f/waflib/Tools/compiler_c.py", line 36, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/usr/pkgsrc/audio/lv2/work/lv2-1.14.0/.waf3-1.8.22-3bda1ef52b63839f28c19902ea6baf8f/waflib/Context.py", line 321, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/usr/pkgsrc/audio/lv2/work/lv2-1.14.0/.waf3-1.8.22-3bda1ef52b63839f28c19902ea6baf8f/waflib/Node.py", line 361, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/usr/pkgsrc/audio/lv2/work/lv2-1.14.0/.waf3-1.8.22-3bda1ef52b63839f28c19902ea6baf8f/waflib/Node.py", line 361, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
```

**Comment by drobilla** [comment]
LV2 1.16.0 is out which builds with Python 3.7.
